import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { Hero } from "../components/Hero";
import { About } from "../components/About";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";
import { AppProvider } from "../context/AppProvider";


export default function Home() {
  let theme = 'dark';

  return (

    <AppProvider>
      <>
        <Head>
          <title>Catalina Olarte</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" type="image/png" href={`/logo-${theme}.png`} />
        </Head>
        <main className="dark:bg-neutral-800 dark:text-slate-50">
          {/* Header */}
          <Header themeVariant={theme} />
          {/* Home */}
          <section id="home" className="snap-start">
            <Hero />
          </section>
          {/* About me */}
          <section id="about" className="snap-center">
            <About />
          </section>
          {/* Projects */}
          <section id="projects" className="snap-center">
            <Projects />
          </section>
          {/* Contect */}
          <section id="contact" className="snap-center">
            <Contact />
          </section>
          {/* Footer */}
          <Footer />
        </main>
      </>
    </AppProvider>

  );
}
